version: '3'

services:
  main:
    container_name: 'calendar-golang-main'
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    container_name: 'calendar-golang-mongo'
    image: mongo
    command: --quiet
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
    - ~/.docker-dbs/mongo/calendar-golang:/data/db